#!/usr/bin/env python3
"""Rebuild the 999 US ROM with modified scripts and Japanese voice SE files.

The original ROM is never modified.  Voice files are inserted at the end of
the existing ``sound`` directory; the four following NitroFS files are shifted
accordingly and the complete FNT/FAT are regenerated by ndspy.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path

import ndspy.rom

from silence_text_bleeps import BleepPatchError, parse_bank


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def shift_folder_ids(folder, threshold: int, amount: int) -> None:
    """Shift folders that begin at or after an inserted file-ID range."""
    for _, child in folder.folders:
        if child.firstID >= threshold:
            child.firstID += amount
        shift_folder_ids(child, threshold, amount)


def validate_voice_files(paths: list[Path]) -> None:
    expected = [f"se_v{index:04d}.se" for index in range(len(paths))]
    actual = [path.name.lower() for path in paths]
    if actual != expected:
        raise ValueError(
            "Voice files must be a contiguous, sorted sequence se_v0000.se, "
            f"se_v0001.se, ...; first mismatch: "
            f"{next(((a, e) for a, e in zip(actual, expected) if a != e), None)}"
        )
    for path in paths:
        data = path.read_bytes()
        if data[:4] != b"SIR0" or b"swdl" not in data[:0x100] or b"sedl" not in data:
            raise ValueError(f"Invalid voice SE container: {path}")


def read_silenced_se_sys(path: Path) -> bytes:
    """Read and strictly validate an optional anti-bleep system SE bank."""
    data = path.read_bytes()
    try:
        parsed = parse_bank(data)
    except BleepPatchError as error:
        raise ValueError(f"Invalid anti-bleep se_sys.se {path}: {error}") from error
    if parsed.state != "silenced":
        raise ValueError(
            f"Anti-bleep se_sys.se is {parsed.state}, expected silenced: {path}"
        )
    return data


def build_rom(
    original: Path,
    output: Path,
    scripts_dir: Path,
    sound_dat: Path,
    voices_dir: Path,
    pad_to_capacity: bool,
    se_sys: Path | None = None,
) -> dict[str, int | str]:
    rom = ndspy.rom.NintendoDSRom.fromFile(str(original))

    script_paths = sorted(scripts_dir.glob("*.fsb"))
    if not script_paths:
        raise ValueError(f"No compiled .fsb files in {scripts_dir}")
    for path in script_paths:
        file_id = rom.filenames.idOf(f"scr/{path.name}")
        if file_id is None:
            raise KeyError(f"Compiled script is not present in ROM: {path.name}")
        data = path.read_bytes()
        if data[:4] != b"SIR0":
            raise ValueError(f"Compiled script is not SIR0: {path}")
        rom.files[file_id] = bytearray(data)

    sound_id = rom.filenames.idOf("etc/sound.dat")
    if sound_id is None:
        raise KeyError("ROM has no etc/sound.dat")
    registry = sound_dat.read_bytes()
    if registry[:4] != b"SIR0":
        raise ValueError("Patched sound.dat is not SIR0")
    rom.files[sound_id] = bytearray(registry)

    se_sys_data: bytes | None = None
    se_sys_id: int | None = None
    if se_sys is not None:
        # Validate the complete SIR0/SEDL/MCRL/SEQ routing before mutating the
        # in-memory ROM.  Merely checking the SIR0 magic would allow an audible
        # or partially patched system bank through.
        se_sys_data = read_silenced_se_sys(se_sys)
        se_sys_id = rom.filenames.idOf("sound/se_sys.se")
        if se_sys_id is None:
            raise KeyError("ROM has no sound/se_sys.se")
        rom.files[se_sys_id] = bytearray(se_sys_data)

    voice_paths = sorted(voices_dir.glob("se_v*.se"))
    if not voice_paths:
        raise ValueError(f"No voice .se files in {voices_dir}")
    validate_voice_files(voice_paths)

    sound_folder = rom.filenames.subfolder("sound")
    if sound_folder is None:
        raise KeyError("ROM has no sound folder")
    insertion_id = sound_folder.firstID + len(sound_folder.files)
    if any(rom.filenames.idOf(f"sound/{path.name}") is not None for path in voice_paths):
        raise ValueError("The input ROM already contains one or more generated voice files")

    count = len(voice_paths)
    rom.files[insertion_id:insertion_id] = [bytearray(path.read_bytes()) for path in voice_paths]
    sound_folder.files.extend(path.name for path in voice_paths)
    shift_folder_ids(rom.filenames, insertion_id, count)
    rom.sortedFileIds = list(range(len(rom.files)))

    data = bytearray(rom.save(updateDeviceCapacity=True))
    capacity = 1 << (rom.deviceCapacity + 17)
    if len(data) > 512 * 1024 * 1024:
        raise ValueError(f"Rebuilt ROM exceeds the Nintendo DS 512 MiB limit: {len(data)} bytes")
    if pad_to_capacity:
        data.extend(b"\xFF" * (capacity - len(data)))

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(data)

    check = ndspy.rom.NintendoDSRom(data)
    if len(check.files) != len(rom.files):
        raise AssertionError("Re-opened ROM has an unexpected FAT file count")
    for index, path in enumerate(voice_paths):
        expected_id = insertion_id + index
        if check.filenames.idOf(f"sound/{path.name}") != expected_id:
            raise AssertionError(f"FNT mismatch for sound/{path.name}")
        if check.files[expected_id][:4] != b"SIR0":
            raise AssertionError(f"FAT payload mismatch for sound/{path.name}")

    if se_sys_data is not None:
        check_se_sys_id = check.filenames.idOf("sound/se_sys.se")
        if check_se_sys_id != se_sys_id:
            raise AssertionError("FNT ID changed unexpectedly for sound/se_sys.se")
        embedded_se_sys = bytes(check.files[check_se_sys_id])
        if embedded_se_sys != se_sys_data:
            raise AssertionError("FAT payload mismatch for sound/se_sys.se")
        if parse_bank(embedded_se_sys).state != "silenced":
            raise AssertionError("Re-opened sound/se_sys.se is not silenced")

    header_crc_stored = struct.unpack_from("<H", data, 0x15E)[0]
    return {
        "bytes": len(data),
        "capacity_bytes": capacity,
        "device_capacity": rom.deviceCapacity,
        "files": len(check.files),
        "voices": count,
        "scripts": len(script_paths),
        "text_bleeps": "silenced" if se_sys_data is not None else "unchanged",
        "header_crc16": f"{header_crc_stored:04x}",
        "sha256": sha256(output),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("original_rom", type=Path)
    parser.add_argument("output_rom", type=Path)
    parser.add_argument("--scripts-dir", type=Path, required=True)
    parser.add_argument("--sound-dat", type=Path, required=True)
    parser.add_argument("--voices-dir", type=Path, required=True)
    parser.add_argument(
        "--se-sys",
        type=Path,
        help=(
            "Replace sound/se_sys.se with a bank validated as fully silenced "
            "by silence_text_bleeps.py."
        ),
    )
    parser.add_argument(
        "--pad-to-capacity",
        action="store_true",
        help="Pad the trimmed image to the power-of-two capacity declared in its header.",
    )
    args = parser.parse_args()
    result = build_rom(
        args.original_rom,
        args.output_rom,
        args.scripts_dir,
        args.sound_dat,
        args.voices_dir,
        args.pad_to_capacity,
        args.se_sys,
    )
    for key, value in result.items():
        print(f"{key}={value}")


if __name__ == "__main__":
    main()
